# Generated by Django 2.2.7 on 2020-01-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
